const tintColor_light = '#f7b733', //active icon color
      tintColor_dark = '#fff',
      listItemBorder_light = "#fff",
      listItemBorder_dark = "#fff",
      buttonBG_light = "#669999",
      buttonBG_dark = "#4d0000",
      buttonTXT_light = "#fff",
      buttonTXT_dark = "#fff",
      heart_light = "#fff",
      heart_dark =  "#fff",
      text_light = "#fff",
      text_dark = "#fff",
      backgroundGrad_light = ['#F2994A', '#F2C94C'],
      backgroundGrad_dark = ['#1a1a1a','#1a1a1a'],
      noteIcon_light = "#334d4d",
      noteIcon_dark = "#fff",
      listItem_light = "#66999980",
      listItem_dark = "#4d0000",
      playerBG_light = "#669999",
      playerBG_dark = "#000",
      playIcon_light = "#fff",
      playIcon_dark = "#fff"
      spinner_light = "#fff",
      spinner_dark = "#fff";

export default {
  tabIconDefault: '#fff',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeText: '#fff',
};

export const lightTheme = {
  theme: "light",
  tintColor: tintColor_light,
  buttonBG:buttonBG_light,
  buttonTXT: buttonTXT_light,
  heart: heart_light,
  text: text_light,
  backgroundGrad: backgroundGrad_light,
  noteIcon: noteIcon_light,
  listItemBorder: listItemBorder_light,
  listItem: listItem_light,
  playIcon: playIcon_light,
  playerBG: playerBG_light,
  spinner: spinner_light,
}
export const darkTheme = {
  theme: "dark",
  tintColor: tintColor_dark,
  buttonBG:buttonBG_dark,
  buttonTXT: buttonTXT_dark,
  heart: heart_dark,
  text: text_dark,
  backgroundGrad: backgroundGrad_dark,
  noteIcon: noteIcon_dark,
  listItemBorder: listItemBorder_dark,
  listItem: listItem_dark,
  playIcon: playIcon_dark,
  playerBG: playerBG_dark,
  spinner: spinner_dark,
}
